/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _APP_H_RPCGEN
#define _APP_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct wejscie {
	char argument;
};
typedef struct wejscie wejscie;

#define zad2 0x23451111
#define wersja 1

#if defined(__STDC__) || defined(__cplusplus)
#define convert 1
extern  int * convert_1(wejscie *, CLIENT *);
extern  int * convert_1_svc(wejscie *, struct svc_req *);
extern int zad2_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define convert 1
extern  int * convert_1();
extern  int * convert_1_svc();
extern int zad2_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_wejscie (XDR *, wejscie*);

#else /* K&R C */
extern bool_t xdr_wejscie ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_APP_H_RPCGEN */
