/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "app.h"

bool_t
xdr_wejscie (XDR *xdrs, wejscie *objp)
{
	register int32_t *buf;

	 if (!xdr_char (xdrs, &objp->argument))
		 return FALSE;
	return TRUE;
}
