/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "app.h"


void
zad2_1(char *host, char argu)
{
	CLIENT *clnt;
	int  *result_1;
	wejscie  convert_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, zad2, wersja, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	convert_1_arg.argument=argu;
	result_1 = convert_1(&convert_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	zad2_1 (host, *argv[2]);
exit (0);
}
