/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "app.h"

int *
convert_1_svc(wejscie *argp, struct svc_req *rqstp)
{
	static int  result;

	printf("Przekonwertowane wejscie: 0x%x\n", argp->argument);
	result = argp->argument;

	return &result;
}
